# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "job5"                            
  table_name_prefix: "t"                           
  table_count: 1
  column_name_prefix: "c"                         
  column_count_min: 500                                                                
  column_count_max: 500                    
  table_rows_min: 1000                                            
  table_rows_max: 5000                                            
                                                                
output:
  create_table_file: "jobs/job5/c.sql"                                     
  drop_table_file: "jobs/job5/d.sql"                                       
  insert_table_file: "jobs/job5/i.sql"                                     
  analyze_table_file: "jobs/job5/a.sql"                                    
  truncate_table_file: "jobs/job5/t.sql"                              
  select_table_file: "jobs/job5/s.sql"                                
  bench_table_file: "jobs/job5/b.sql"                                      

# ----------------------------------------
