dsn: "host=c-raodb port=5432 dbname=postgres user=postgres password=postgres"

procedures:
  - name: "bench.p_t_hash1"
    kind: "procedure"
    param_style: "named"
    params:
      - { name: "p_refcur", type: "refcursor" }
      - { name: "p_id",      type: "bigint" }

  - name: "bench.p_t_hash2"
    kind: "procedure"
    param_style: "named"
    params:
      - { name: "p_refcur", type: "refcursor" }
      - { name: "p_id",      type: "bigint" }

  - name: "bench.p_t_hash3"
    kind: "procedure"
    param_style: "named"
    params:
      - { name: "p_refcur", type: "refcursor" }
      - { name: "p_id",      type: "bigint" }

  - name: "bench.f_t_hash1"
    kind: "function"
    param_style: "named"
    params:
      - { name: "p_id",      type: "bigint" }

  - name: "bench.f_t_hash2"
    kind: "function"
    param_style: "named"
    params:
      - { name: "p_id",      type: "bigint" }

  - name: "bench.f_t_hash3"
    kind: "function"
    param_style: "named"
    params:
      - { name: "p_id",      type: "bigint" }


