# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "pxses"                            
  table_name_prefix: "t"                           
  table_count: 1000                                 
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 5                    
  table_rows_min: 100                                            
  table_rows_max: 500                                            
                                                                
output:
  create_table_file: "scripts/pxses/c.sql"                                     
  drop_table_file: "scripts/pxses/d.sql"                                       
  insert_table_file: "scripts/pxses/i.sql"                                     
  analyze_table_file: "scripts/pxses/a.sql"                                    
  truncate_table_file: "scripts/pxses/t.sql"                              
  select_table_file: "scripts/pxses/s.sql"                                

# ----------------------------------------
