# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "job4"                            
  table_name_prefix: "t"                           
  table_count: 1
  column_name_prefix: "c"                         
  column_count_min: 10                                                                
  column_count_max: 50                    
  table_rows_min: 1000000                                            
  table_rows_max: 1000000                                            
                                                                
output:
  create_table_file: "jobs/job4/c.sql"                                     
  drop_table_file: "jobs/job4/d.sql"                                       
  insert_table_file: "jobs/job4/i.sql"                                     
  analyze_table_file: "jobs/job4/a.sql"                                    
  truncate_table_file: "jobs/job4/t.sql"                              
  select_table_file: "jobs/job4/s.sql"                                
  bench_table_file: "jobs/job4/b.sql"                                      

# ----------------------------------------
