# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "job2"                            
  table_name_prefix: "t"                           
  table_count: 100                                 
  column_name_prefix: "c"                         
  column_count_min: 10                                                                
  column_count_max: 20                    
  table_rows_min: 10000                                            
  table_rows_max: 50000                                            
                                                                
output:
  create_table_file: "jobs/job2/c.sql"                                     
  drop_table_file: "jobs/job2/d.sql"                                       
  insert_table_file: "jobs/job2/i.sql"                                     
  analyze_table_file: "jobs/job2/a.sql"                                    
  truncate_table_file: "jobs/job2/t.sql"                              
  select_table_file: "jobs/job2/s.sql"                                
  bench_table_file: "jobs/job2/b.sql"                                      

# ----------------------------------------
