# ================================================================================
# Specify tasks to be performed by python script.Group tasks. 
#
# Group attributes: 
#    name: <group-name>
#    parallelism: 1
#    skip: false
#    repeat: 1
#
# Task attributges:     
#    id: <task-name>
#    sql: "REFRESH MATERIALIZED VIEW CONCURRENTLY mv_sales;"
#    sql_file
#    depends_on: [task1, task2]
#    retries: 3
#    retry_delay_sec: 5
#    statement_timeout_sec: 600
#    timeout: 
#    on_failure: continue

# ================================================================================
database:
  dsn: "host=c-raodb port=5432 dbname=postgres user=postgres password=postgres"

execution:
  dry_run: false   # true = no SQL execution
  default_on_failure: abort  # skip | continue | abort

defaults:
  retries: 1
  retry_delay_sec: 5
  statement_timeout_sec: 300
  repeat: 1
  skip: false

groups:
# ----------------------------------------
  - name: drop_domain

    tasks:
      - id: drop_part_hash_domains
        sql_file: "scripts/bench/sql/drop_domain_part_hash.sql"

      - id: drop_part_list_domains
        sql_file: "scripts/bench/sql/drop_domain_part_list.sql"

      - id: drop_part_range_domains
        sql_file: "scripts/bench/sql/drop_domain_part_range.sql"

      - id: drop_part_random_domains
        sql_file: "scripts/bench/sql/drop_domain_part_random.sql"

      - id: drop_size_small_domains
        sql_file: "scripts/bench/sql/drop_domain_size_small.sql"

      - id: drop_size_medium_domains
        sql_file: "scripts/bench/sql/drop_domain_size_medium.sql"

      - id: drop_size_large_domains
        sql_file: "scripts/bench/sql/drop_domain_size_large.sql"

      - id: drop_size_wide_domains
        sql_file: "scripts/bench/sql/drop_domain_size_wide.sql"

# ----------------------------------------
  - name: drop_types

    tasks:
      - id: drop_part_hash_types
        sql_file: "scripts/bench/sql/drop_type_part_hash.sql"

      - id: drop_part_list_types
        sql_file: "scripts/bench/sql/drop_type_part_list.sql"

      - id: drop_part_range_types
        sql_file: "scripts/bench/sql/drop_type_part_range.sql"

      - id: drop_part_random_types
        sql_file: "scripts/bench/sql/drop_type_part_random.sql"

      - id: drop_size_small_types
        sql_file: "scripts/bench/sql/drop_type_size_small.sql"

      - id: drop_size_medium_types
        sql_file: "scripts/bench/sql/drop_type_size_medium.sql"

      - id: drop_size_large_types
        sql_file: "scripts/bench/sql/drop_type_size_large.sql"

      - id: drop_size_wide_types
        sql_file: "scripts/bench/sql/drop_type_size_wide.sql"

# ----------------------------------------
  - name: drop_views

    tasks:
      - id: drop_part_hash_views
        sql_file: "scripts/bench/sql/drop_view_part_hash.sql"

      - id: drop_part_list_views
        sql_file: "scripts/bench/sql/drop_view_part_list.sql"

      - id: drop_part_range_views
        sql_file: "scripts/bench/sql/drop_view_part_range.sql"

      - id: drop_part_random_views
        sql_file: "scripts/bench/sql/drop_view_part_random.sql"

      - id: drop_size_small_views
        sql_file: "scripts/bench/sql/drop_view_size_small.sql"

      - id: drop_size_medium_views
        sql_file: "scripts/bench/sql/drop_view_size_medium.sql"

      - id: drop_size_large_views
        sql_file: "scripts/bench/sql/drop_view_size_large.sql"

      - id: drop_size_wide_views
        sql_file: "scripts/bench/sql/drop_view_size_wide.sql"

# ----------------------------------------
  - name: drop_procedures

    tasks:
      - id: drop_part_hash_procedures
        sql_file: "scripts/bench/sql/drop_proc_part_hash.sql"

      - id: drop_part_list_procedures
        sql_file: "scripts/bench/sql/drop_proc_part_list.sql"

      - id: drop_part_range_procedures
        sql_file: "scripts/bench/sql/drop_proc_part_range.sql"

      - id: drop_part_random_procedures
        sql_file: "scripts/bench/sql/drop_proc_part_random.sql"

      - id: drop_size_small_procedures
        sql_file: "scripts/bench/sql/drop_proc_size_small.sql"

      - id: drop_size_medium_procedures
        sql_file: "scripts/bench/sql/drop_proc_size_medium.sql"

      - id: drop_size_large_procedures
        sql_file: "scripts/bench/sql/drop_proc_size_large.sql"

      - id: drop_size_wide_procedures
        sql_file: "scripts/bench/sql/drop_proc_size_wide.sql"

# ----------------------------------------
  - name: drop_functions

    tasks:
      - id: drop_part_hash_functions
        sql_file: "scripts/bench/sql/drop_func_part_hash.sql"

      - id: drop_part_list_functions
        sql_file: "scripts/bench/sql/drop_func_part_list.sql"

      - id: drop_part_range_functions
        sql_file: "scripts/bench/sql/drop_func_part_range.sql"

      - id: drop_part_random_functions
        sql_file: "scripts/bench/sql/drop_func_part_random.sql"

      - id: drop_size_small_functions
        sql_file: "scripts/bench/sql/drop_func_size_small.sql"

      - id: drop_size_medium_functions
        sql_file: "scripts/bench/sql/drop_func_size_medium.sql"

      - id: drop_size_large_functions
        sql_file: "scripts/bench/sql/drop_func_size_large.sql"

      - id: drop_size_wide_functions
        sql_file: "scripts/bench/sql/drop_func_size_wide.sql"

# ----------------------------------------
  - name: drop_tables

    tasks:
      - id: drop_part_hash_tables
        sql_file: "scripts/bench/sql/drop_table_part_hash.sql"

      - id: drop_part_list_tables
        sql_file: "scripts/bench/sql/drop_table_part_list.sql"

      - id: drop_part_range_tables
        sql_file: "scripts/bench/sql/drop_table_part_range.sql"

      - id: drop_part_random_tables
        sql_file: "scripts/bench/sql/drop_table_part_random.sql"

      - id: drop_size_small_tables
        sql_file: "scripts/bench/sql/drop_table_size_small.sql"

      - id: drop_size_medium_tables
        sql_file: "scripts/bench/sql/drop_table_size_medium.sql"

      - id: drop_size_large_tables
        sql_file: "scripts/bench/sql/drop_table_size_large.sql"

      - id: drop_size_wide_tables
        sql_file: "scripts/bench/sql/drop_table_size_wide.sql"

# ----------------------------------------
# END
# ----------------------------------------
