# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "t_list"                           
  table_count: 3
  column_name_prefix: "c"                         
  column_count_min: 4                                                                
  column_count_max: 8                    
  table_rows_min: 1000                                            
  table_rows_max: 5000                                            

  partition:
    enabled: true          # false = normal tables
    type: list           # random | range | list | hash
    partition_count_min: 3
    partition_count_max: 8
    allowed_column_types: ["integer", "date"]
                                                                
output:
  create_table_file: "scripts/bench/sql/create_table_part_list.sql"                                     
  drop_table_file: "scripts/bench/sql/drop_table_part_list.sql"                                       
  insert_table_file: "scripts/bench/sql/insert_table_part_list.sql"                                     
  analyze_table_file: "scripts/bench/sql/analyze_table_part_list.sql"                                    
  truncate_table_file: "scripts/bench/sql/truncate_table_part_list.sql"                              
  select_table_file: "scripts/bench/sql/select_table_part_list.sql"                                
#
  create_view_file: "scripts/bench/sql/create_view_part_list.sql"                                
  drop_view_file: "scripts/bench/sql/drop_view_part_list.sql"                                
#
  create_proc_file: "scripts/bench/sql/create_proc_part_list.sql"                                
  call_proc_file: "scripts/bench/sql/call_proc_part_list.sql"                                
  drop_proc_file: "scripts/bench/sql/drop_proc_part_list.sql"                                
#
  create_func_file: "scripts/bench/sql/create_func_part_list.sql"                                
  call_func_file: "scripts/bench/sql/call_func_part_list.sql"                                
  drop_func_file: "scripts/bench/sql/drop_func_part_list.sql"                                
#
  create_type_file: "scripts/bench/sql/create_type_part_list.sql"                                
  drop_type_file: "scripts/bench/sql/drop_type_part_list.sql"                                
#
  create_domain_file: "scripts/bench/sql/create_domain_part_list.sql"                                
  drop_domain_file: "scripts/bench/sql/drop_domain_part_list.sql"                                
#

# ----------------------------------------
