# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "tpx"                           
  table_count: 10
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 6                    
  table_rows_min: 1000                                            
  table_rows_max: 5000                                            

  partition:
    enabled: true          # false = normal tables
    type: random           # random | random | list | hash
    partition_count_min: 3
    partition_count_max: 10
    allowed_column_types: ["integer", "date"]
                                                                
output:
  create_table_file: "scripts/bench/sql/create_table_part_random.sql"                                     
  drop_table_file: "scripts/bench/sql/drop_table_part_random.sql"                                       
  insert_table_file: "scripts/bench/sql/insert_table_part_random.sql"                                     
  analyze_table_file: "scripts/bench/sql/analyze_table_part_random.sql"                                    
  truncate_table_file: "scripts/bench/sql/truncate_table_part_random.sql"                              
  select_table_file: "scripts/bench/sql/select_table_part_random.sql"                                
#
  create_view_file: "scripts/bench/sql/create_view_part_random.sql"                                
  drop_view_file: "scripts/bench/sql/drop_view_part_random.sql"                                
#
  create_proc_file: "scripts/bench/sql/create_proc_part_random.sql"                                
  call_proc_file: "scripts/bench/sql/call_proc_part_random.sql"                                
  drop_proc_file: "scripts/bench/sql/drop_proc_part_random.sql"                                
#
  create_func_file: "scripts/bench/sql/create_func_part_random.sql"                                
  call_func_file: "scripts/bench/sql/call_func_part_random.sql"                                
  drop_func_file: "scripts/bench/sql/drop_func_part_random.sql"                                
#
  create_type_file: "scripts/bench/sql/create_type_part_random.sql"                                
  drop_type_file: "scripts/bench/sql/drop_type_part_random.sql"                                
#
  create_domain_file: "scripts/bench/sql/create_domain_part_random.sql"                                
  drop_domain_file: "scripts/bench/sql/drop_domain_part_random.sql"                                
  bind_select_file: "scripts/bench/sql/bind_select_part_random.sql"                                
  bind_insert_file: "scripts/bench/sql/bind_insert_part_random.sql"                                
  bind_update_file: "scripts/bench/sql/bind_update_part_random.sql"                                
  bind_delete_file: "scripts/bench/sql/bind_delete_part_random.sql"                                
#
#

# ----------------------------------------
