# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "tsw"                           
  table_count: 10
  column_name_prefix: "c"                         
  column_count_min: 100                                                                
  column_count_max: 200                   
  table_rows_min: 100                                            
  table_rows_max: 200                                            
                                                                
output:
  create_table_file: "scripts/bench/sql/create_table_size_wide.sql"                                     
  drop_table_file: "scripts/bench/sql/drop_table_size_wide.sql"                                       
  insert_table_file: "scripts/bench/sql/insert_table_size_wide.sql"                                     
  analyze_table_file: "scripts/bench/sql/analyze_table_size_wide.sql"                                    
  truncate_table_file: "scripts/bench/sql/truncate_table_size_wide.sql"                              
  select_table_file: "scripts/bench/sql/select_table_size_wide.sql"                                
#
  create_view_file: "scripts/bench/sql/create_view_size_wide.sql"                                
  drop_view_file: "scripts/bench/sql/drop_view_size_wide.sql"                                
#
  create_proc_file: "scripts/bench/sql/create_proc_size_wide.sql"                                
  call_proc_file: "scripts/bench/sql/call_proc_size_wide.sql"                                
  drop_proc_file: "scripts/bench/sql/drop_proc_size_wide.sql"                                
#
  create_func_file: "scripts/bench/sql/create_func_size_wide.sql"                                
  call_func_file: "scripts/bench/sql/call_func_size_wide.sql"                                
  drop_func_file: "scripts/bench/sql/drop_func_size_wide.sql"                                
#
  create_type_file: "scripts/bench/sql/create_type_size_wide.sql"                                
  drop_type_file: "scripts/bench/sql/drop_type_size_wide.sql"                                
#
  create_domain_file: "scripts/bench/sql/create_domain_size_wide.sql"                                
  drop_domain_file: "scripts/bench/sql/drop_domain_size_wide.sql"                                
#

# ----------------------------------------
