# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "tss"                           
  table_count: 10                                 
  column_name_prefix: "c"                         
  column_count_min: 5                                                                
  column_count_max: 10                    
  table_rows_min: 10                                            
  table_rows_max: 20                                            
                                                                
output:
  create_table_file: "scripts/bench/sql/create_table_size_small.sql"                                     
  drop_table_file: "scripts/bench/sql/drop_table_size_small.sql"                                       
  insert_table_file: "scripts/bench/sql/insert_table_size_small.sql"                                     
  analyze_table_file: "scripts/bench/sql/analyze_table_size_small.sql"                                    
  truncate_table_file: "scripts/bench/sql/truncate_table_size_small.sql"                              
  select_table_file: "scripts/bench/sql/select_table_size_small.sql"                                
#
  create_view_file: "scripts/bench/sql/create_view_size_small.sql"                                
  drop_view_file: "scripts/bench/sql/drop_view_size_small.sql"                                
#
  create_proc_file: "scripts/bench/sql/create_proc_size_small.sql"                                
  call_proc_file: "scripts/bench/sql/call_proc_size_small.sql"                                
  drop_proc_file: "scripts/bench/sql/drop_proc_size_small.sql"                                
#
  create_func_file: "scripts/bench/sql/create_func_size_small.sql"                                
  call_func_file: "scripts/bench/sql/call_func_size_small.sql"                                
  drop_func_file: "scripts/bench/sql/drop_func_size_small.sql"                                
#
  create_type_file: "scripts/bench/sql/create_type_size_small.sql"                                
  drop_type_file: "scripts/bench/sql/drop_type_size_small.sql"                                
#
  create_domain_file: "scripts/bench/sql/create_domain_size_small.sql"                                
  drop_domain_file: "scripts/bench/sql/drop_domain_size_small.sql"                                
  bind_select_file: "scripts/bench/sql/bind_select_size_small.sql"                                
  bind_insert_file: "scripts/bench/sql/bind_insert_size_small.sql"                                
  bind_update_file: "scripts/bench/sql/bind_update_size_small.sql"                                
  bind_delete_file: "scripts/bench/sql/bind_delete_size_small.sql"                                
#
#

# ----------------------------------------
