# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "part_random"                            
  table_name_prefix: "t"                           
  table_count: 100
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 6                    
  table_rows_min: 100                                            
  table_rows_max: 500                                            

  partition:
    enabled: true          # false = normal tables
    type: random           # random | random | list | hash
    partition_count_min: 3
    partition_count_max: 10
    allowed_column_types: ["integer", "date"]
                                                                
output:
  create_table_file: "scripts/part_random/c.sql"                                     
  drop_table_file: "scripts/part_random/d.sql"                                       
  insert_table_file: "scripts/part_random/i.sql"                                     
  analyze_table_file: "scripts/part_random/a.sql"                                    
  truncate_table_file: "scripts/part_random/t.sql"                              
  select_table_file: "scripts/part_random/s.sql"                                

# ----------------------------------------
