# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "job1"                            
  table_name_prefix: "t"                           
  table_count: 10                                 
  column_name_prefix: "c"                         
  column_count_min: 5                                                                
  column_count_max: 10                    
  table_rows_min: 100                                            
  table_rows_max: 500                                            
                                                                
output:
  create_table_file: "jobs/job1/c.sql"                                     
  drop_table_file: "jobs/job1/d.sql"                                       
  insert_table_file: "jobs/job1/i.sql"                                     
  analyze_table_file: "jobs/job1/a.sql"                                    
  truncate_table_file: "jobs/job1/t.sql"                              
  select_table_file: "jobs/job1/s.sql"                                
  bench_table_file: "jobs/job1/b.sql"                                      

# ----------------------------------------
