# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "part_range"                            
  table_name_prefix: "t"                           
  table_count: 100
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 6                    
  table_rows_min: 1000                                            
  table_rows_max: 5000                                            

  partition:
    enabled: true          # false = normal tables
    type: range           # random | range | list | hash
    partition_count_min: 5
    partition_count_max: 10
    allowed_column_types: ["integer", "date"]
                                                                
output:
  create_table_file: "scripts/part_range/c.sql"                                     
  drop_table_file: "scripts/part_range/d.sql"                                       
  insert_table_file: "scripts/part_range/i.sql"                                     
  analyze_table_file: "scripts/part_range/a.sql"                                    
  truncate_table_file: "scripts/part_range/t.sql"                              
  select_table_file: "scripts/part_range/s.sql"                                
  create_proc_file: "scripts/part_range/p.sql"  
  create_func_file: "scripts/part_range/f.sql"  


# ----------------------------------------
