# ================================================================================
# Specify tasks to be performed by python script.Group tasks. 
#
# Group attributes: 
#    name: <group-name>
#    parallelism: 1
#    skip: false
#    repeat: 1
#
# Task attributges:     
#    id: <task-name>
#    sql: "REFRESH MATERIALIZED VIEW CONCURRENTLY mv_sales;"
#    sql_file
#    depends_on: [task1, task2]
#    retries: 3
#    retry_delay_sec: 5
#    statement_timeout_sec: 600
#    timeout: 
#    on_failure: continue

# ================================================================================
database:
  dsn: "host=c-raodb port=5432 dbname=postgres user=postgres password=postgres"

execution:
  dry_run: false   # true = no SQL execution
  default_on_failure: abort  # skip | continue | abort

defaults:
  retries: 1
  retry_delay_sec: 5
  statement_timeout_sec: 300
  repeat: 1
  skip: false

groups:
# ----------------------------------------
  - name: cleanup

    tasks:
      - id: drop_part_hash_tables
        sql_file: "scripts/bench/d_part_hash.sql"

      - id: drop_part_list_tables
        sql_file: "scripts/bench/d_part_list.sql"

      - id: drop_part_range_tables
        sql_file: "scripts/bench/d_part_range.sql"

      - id: drop_part_list_tables
        sql_file: "scripts/bench/d_part_list.sql"

      - id: drop_size_small_tables
        sql_file: "scripts/bench/d_size_small.sql"

      - id: drop_size_medium_tables
        sql_file: "scripts/bench/d_size_medium.sql"

      - id: drop_size_large_tables
        sql_file: "scripts/bench/d_size_large.sql"

      - id: drop_size_wide_tables
        sql_file: "scripts/bench/d_size_wide.sql"

# ----------------------------------------
  - name: create

    tasks:
      - id: create_part_hash_tables
        sql_file: "scripts/bench/c_part_hash.sql"

      - id: create_part_list_tables
        sql_file: "scripts/bench/c_part_list.sql"

      - id: create_part_range_tables
        sql_file: "scripts/bench/c_part_range.sql"

      - id: create_part_list_tables
        sql_file: "scripts/bench/c_part_list.sql"

      - id: create_size_small_tables
        sql_file: "scripts/bench/c_size_small.sql"

      - id: create_size_medium_tables
        sql_file: "scripts/bench/c_size_medium.sql"

      - id: create_size_large_tables
        sql_file: "scripts/bench/c_size_large.sql"

      - id: create_size_wide_tables
        sql_file: "scripts/bench/c_size_wide.sql"

# ----------------------------------------
  - name: truncate

    tasks:
      - id: truncate_part_hash_tables
        sql_file: "scripts/bench/t_part_hash.sql"

      - id: truncate_part_list_tables
        sql_file: "scripts/bench/t_part_list.sql"

      - id: truncate_part_range_tables
        sql_file: "scripts/bench/t_part_range.sql"

      - id: truncate_part_list_tables
        sql_file: "scripts/bench/t_part_list.sql"

      - id: truncate_size_small_tables
        sql_file: "scripts/bench/t_size_small.sql"

      - id: truncate_size_medium_tables
        sql_file: "scripts/bench/t_size_medium.sql"

      - id: truncate_size_large_tables
        sql_file: "scripts/bench/t_size_large.sql"

      - id: truncate_size_wide_tables
        sql_file: "scripts/bench/t_size_wide.sql"

# ----------------------------------------
  - name: insert

    tasks:
      - id: insert_part_hash_tables
        sql_file: "scripts/bench/i_part_hash.sql"

      - id: insert_part_list_tables
        sql_file: "scripts/bench/i_part_list.sql"

      - id: insert_part_range_tables
        sql_file: "scripts/bench/i_part_range.sql"

      - id: insert_part_list_tables
        sql_file: "scripts/bench/i_part_list.sql"

      - id: insert_size_small_tables
        sql_file: "scripts/bench/i_size_small.sql"

      - id: insert_size_medium_tables
        sql_file: "scripts/bench/i_size_medium.sql"

      - id: insert_size_large_tables
        sql_file: "scripts/bench/i_size_large.sql"

      - id: insert_size_wide_tables
        sql_file: "scripts/bench/i_size_wide.sql"

# ----------------------------------------
  - name: analyze

    tasks:
      - id: analyze_part_hash_tables
        sql_file: "scripts/bench/a_part_hash.sql"

      - id: analyze_part_list_tables
        sql_file: "scripts/bench/a_part_list.sql"

      - id: analyze_part_range_tables
        sql_file: "scripts/bench/a_part_range.sql"

      - id: analyze_part_list_tables
        sql_file: "scripts/bench/a_part_list.sql"

      - id: analyze_size_small_tables
        sql_file: "scripts/bench/a_size_small.sql"

      - id: analyze_size_medium_tables
        sql_file: "scripts/bench/a_size_medium.sql"

      - id: analyze_size_large_tables
        sql_file: "scripts/bench/a_size_large.sql"

      - id: analyze_size_wide_tables
        sql_file: "scripts/bench/a_size_wide.sql"

# ----------------------------------------
  - name: count

    tasks:
      - id: count_part_hash_tables
        sql_file: "scripts/bench/s_part_hash.sql"

      - id: count_part_list_tables
        sql_file: "scripts/bench/s_part_list.sql"

      - id: count_part_range_tables
        sql_file: "scripts/bench/s_part_range.sql"

      - id: count_part_list_tables
        sql_file: "scripts/bench/s_part_list.sql"

      - id: count_size_small_tables
        sql_file: "scripts/bench/s_size_small.sql"

      - id: count_size_medium_tables
        sql_file: "scripts/bench/s_size_medium.sql"

      - id: count_size_large_tables
        sql_file: "scripts/bench/s_size_large.sql"

      - id: count_size_wide_tables
        sql_file: "scripts/bench/s_size_wide.sql"

# ----------------------------------------
  - name: create_procedures

    tasks:
      - id: create_proc_part_hash_tables
        sql_file: "scripts/bench/p_part_hash.sql"

      - id: create_proc_part_list_tables
        sql_file: "scripts/bench/p_part_list.sql"

      - id: create_proc_part_range_tables
        sql_file: "scripts/bench/p_part_range.sql"

      - id: create_proc_part_list_tables
        sql_file: "scripts/bench/p_part_list.sql"

      - id: create_proc_size_small_tables
        sql_file: "scripts/bench/p_size_small.sql"

      - id: create_proc_size_medium_tables
        sql_file: "scripts/bench/p_size_medium.sql"

      - id: create_proc_size_large_tables
        sql_file: "scripts/bench/p_size_large.sql"

      - id: create_proc_size_wide_tables
        sql_file: "scripts/bench/p_size_wide.sql"

# ----------------------------------------
  - name: create_functions

    tasks:
      - id: create_func__part_hash_tables
        sql_file: "scripts/bench/f_part_hash.sql"

      - id: create_func__part_list_tables
        sql_file: "scripts/bench/f_part_list.sql"

      - id: create_func__part_range_tables
        sql_file: "scripts/bench/f_part_range.sql"

      - id: create_func__part_list_tables
        sql_file: "scripts/bench/f_part_list.sql"

      - id: create_func__size_small_tables
        sql_file: "scripts/bench/f_size_small.sql"

      - id: create_func__size_medium_tables
        sql_file: "scripts/bench/f_size_medium.sql"

      - id: create_func__size_large_tables
        sql_file: "scripts/bench/f_size_large.sql"

      - id: create_func__size_wide_tables
        sql_file: "scripts/bench/f_size_wide.sql"

# ----------------------------------------
# END
# ----------------------------------------
