# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "t_random"                           
  table_count: 10
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 6                    
  table_rows_min: 1000                                            
  table_rows_max: 5000                                            

  partition:
    enabled: true          # false = normal tables
    type: random           # random | random | list | hash
    partition_count_min: 3
    partition_count_max: 10
    allowed_column_types: ["integer", "date"]
                                                                
output:
  create_table_file: "scripts/bench/c_part_random.sql"                                     
  drop_table_file: "scripts/bench/d_part_random.sql"                                       
  insert_table_file: "scripts/bench/i_part_random.sql"                                     
  analyze_table_file: "scripts/bench/a_part_random.sql"                                    
  truncate_table_file: "scripts/bench/t_part_random.sql"                              
  select_table_file: "scripts/bench/s_part_random.sql"                                
  create_proc_file: "scripts/bench/p_part_random.sql"  
  create_func_file: "scripts/bench/f_part_random.sql"  

# ----------------------------------------
