# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "t_large"                           
  table_count: 10                                 
  column_name_prefix: "c"                         
  column_count_min: 3                                                                
  column_count_max: 5                    
  table_rows_min: 100000                                            
  table_rows_max: 200000                                            
                                                                
output:
  create_table_file: "scripts/bench/c_size_large.sql"                                     
  drop_table_file: "scripts/bench/d_size_large.sql"                                       
  insert_table_file: "scripts/bench/i_size_large.sql"                                     
  analyze_table_file: "scripts/bench/a_size_large.sql"                                    
  truncate_table_file: "scripts/bench/t_size_large.sql"                              
  select_table_file: "scripts/bench/s_size_large.sql"                                
  create_proc_file: "scripts/bench/p_size_large.sql"                                
  create_func_file: "scripts/bench/f_size_large.sql"                                

# ----------------------------------------
