# ----------------------------------------
# configuration for tabgen.py
input:
  table_schema: "bench"                            
  table_name_prefix: "t_wide"                           
  table_count: 10
  column_name_prefix: "c"                         
  column_count_min: 100                                                                
  column_count_max: 200                   
  table_rows_min: 100                                            
  table_rows_max: 200                                            
                                                                
output:
  create_table_file: "scripts/bench/c_size_wide.sql"                                     
  drop_table_file: "scripts/bench/d_size_wide.sql"                                       
  insert_table_file: "scripts/bench/i_size_wide.sql"                                     
  analyze_table_file: "scripts/bench/a_size_wide.sql"                                    
  truncate_table_file: "scripts/bench/t_size_wide.sql"                              
  select_table_file: "scripts/bench/s_size_wide.sql"                                
  create_proc_file: "scripts/bench/p_size_wide.sql"    
  create_func_file: "scripts/bench/f_size_wide.sql"    

# ----------------------------------------
